baseURL = "http://dupe.sh/"
languageCode = "en-us"
title = "dupe.sh"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[params]
    byline = "jaunts through the software frontiers"
    link = "https://dupe.codes"
    linkText = "dupe.codes"
    aboutMeLink = "https://dupe.codes/about+me"
    githubLink = "https://github.com/dupe-codes"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "blog rss feed"
    url = "/blog.xml"
    weight = 2
  [[menu.main]]
    name = "game projects"
    url = "/project/gamedev"
    weight = 3

