baseURL = "http://dupe.sh/"
languageCode = "en-us"
title = "dupe.sh"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true

[params]
    byline = "jaunts through the software frontiers"
    link = "https://dupe.codes"
    linkText = "dupe.codes"
    aboutMeLink = "https://dupe.codes/about+me"
    githubLink = "https://github.com/njdup"

[menu]
  [[menu.main]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "example project"
    url = "/project/example"
    weight = 2
  [[menu.main]]
    name = "test html only"
    url = "/project/test"
    weight = 3
  [[menu.main]]
    name = "test quarto file"
    url = "/notebook/hello"
    weight = 4
  [[menu.main]]
    name = "test quarto 2"
    url = "/notebook/hello2"
    weight = 5
  [[menu.main]]
    name = "kodemo test"
    url = "/walkthrough/kodemo"
    weight = 6

